[package]
name = "antbyte"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
rand = "*"
regex = "*"
clap = { version = "*", features = ["derive"], optional = true }
gif = { version = "*", optional = true }
notify = { version = "*", optional = true }

[features]
default = ["clap", "extras"]
# default = ["clap"]
clap = ["dep:clap"]
extras = ["dep:gif", "notify"]
