[package]
name = "antbyte"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[dependencies]
anyhow = "*"
clap = { version = "4.5.47", features = ["derive"] }
rand = "*"
regex = "*"
