[package]
name = "antbyte"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
clap = { version = "4.5.47", features = ["derive"], optional = true }
rand = "*"
regex = "*"

[features]
default = ["clap"]
clap = ["dep:clap"]
