// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Peripheral } from "./Peripheral";

export type PeripheralBit = { peripheral: Peripheral, bit: number, };
