// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderMode } from "./BorderMode";
import type { ColorMode } from "./ColorMode";
import type { StartingPos } from "./StartingPos";

export type WorldConfig = { 
/**
 * width in pixels
 */
width: number, 
/**
 * height in pixels
 */
height: number, 
/**
 * rendered frames per second
 */
fps: number | null, 
/**
 * simulated ticks per frame (defaults to 1)
 */
speed: number | null, 
/**
 * simulation tick limit
 */
ticks: number | null, sleep: number | null, looping: boolean, border_mode: BorderMode, starting_pos: StartingPos, color_mode: ColorMode, noise_seed: number | null, hide_title: boolean, description: string, };
